language: go
go:
  - master
  - stable
  - "1.14"
  - "1.13"
  - "1.12"
env:
  - GO111MODULE=on
install:
  - go get -t ./...
script:
# v1
  - go test -v .
# v2
  - cd v2
  - go test -v .
  - cd ..
after_success:
  - cd v2
  - curl -s https://codecov.io/bash | bash
